export const SET_CREDIT_CARD_COMPANY = 'SET_CREDIT_CARD_COMPANY';
export const SET_CREDIT_CARD_NAME = 'SET_CREDIT_CARD_NAME';
export const SET_CREDIT_CARD_NUMBER = 'SET_CREDIT_CARD_NUMBER';
export const SET_CREDIT_EXPIRATION_DATE = 'SET_CREDIT_EXPIRATION_DATE';
export const SET_CREDIT_CARD_OWNER_NAME = 'SET_CREDIT_CARD_OWNER_NAME';
export const SET_CREDIT_SECURITY_CODE = 'SET_CREDIT_SECURITY_CODE';
export const SET_CREDIT_CARD_PASSWORD = 'SET_CREDIT_CARD_PASSWORD';
